title:               川崎ソリュジャーズG
url:                 https://soldiersg.github.io/kawasaki-soldiersg
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Kawasaki Soldiers G
  url:               https://soldiersg.github.io/kawasaki-soldiersg
#  email:             

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist